### ISSUE TITLE
Random questions

### ISSUE THREAD

**Issue by ghost** [Gegy/tic-tacs#1]
A-Should I trust worlds made with this mod?
C-Is it compatible with jellysquid's mods and act-two?
EDIT:A to C,
NICE

**Comment by Gegy** [comment]
A. For now, definitely not! :P The mod is still very much unstable 😅 But, that will be improving in the future :)
C. I've only tested with phosphor- there's the possibility for incompatibility with lithium, but at some point I want to ensure that there's compatibility. Also, act-two is tic-tacs :) Renamed because this has far exceeded the initial scope of the mod

**Comment by ghost** [comment]
thanks
