### ISSUE TITLE
Chunk loading speed request

### ISSUE THREAD

**Issue by jojos38** [Gegy/tic-tacs#16]
Hi! Your mod is really awesome, keep it up, I was wondering if it would be possible to have an option so that the chunks load faster? The chunk loading process is indeed multithreaded now but it still feels quite slow, using Elytras for example still move too fast for the chunks to load.

Thanks in advance!

**Comment by Gegy** [comment]
Making chunk generation faster is the purpose of this mod :P 
The goal is to keep improving on it over time, and there is definitely still a lot of room for improvement! Currently unfortunately the main bottleneck is lighting, which is much more challenging to improve performance with. I recommend installing [Phosphor](github.com/jellysquid3/phosphor-fabric) if you haven't already. :)

**Comment by jojos38** [comment]
I did indeed install Phosphor, and managed to get up to 80 chunk render distance but yeah, when I go from one chunk to another I have freezes due to lightning.
I noticed the mods puts nCpuCore - 2 as the core number (I have 8 cores it puts 6), since I do have multithreading, should I put that to 14? or is there a purpose for not using multithreading please?

**Comment by Gegy** [comment]
Adding more threads can help up to a certain point, but it will give diminishing returns pretty quick. This is mainly because most of the time the threads will just be waiting on the lighting engine anyway. 4 threads is probably the most that will have any meaningful sort of impact.

**Comment by jaskarth** [comment]
6 is the max that it'll to to by default. You can increase the number but you may start to see diminishing returns :/

**Comment by jojos38** [comment]
I see, thank you very much for your answers, I'll keep it to 6 then, hope you'll get it even better over the time!

**Comment by jojos38** [comment]
I also profit of this to report an issue where sometimes one chunk or two do not generate when I create a new world, and it cause it to stay stuck at 99% or 97%, I don't know if it's a known bug

**Comment by ghost** [comment]
**Some information may be wrong,I am NOT an expert**
@jojos38 Have you tried pre-generating chunks?
-when you visit a chunk for the first time it is going to appear slower than the second /third/forth...etc time,that is because the game has to generate the terrain (load it **I don't know the term "load" should be used** ) and render it but, for the second time the terrian is already generated so it has only to load the chunk and render it.
-You can pregenerate chunks using mods like:https://www.curseforge.com/minecraft/mc-mods/chunk-pregenerator-fabric:
I am not sure if it has parity with vanilla.
-You can use datapacks like:https://github.com/GoldenDelicios/world-pregen
I don't know if it still works.
-You can do it manually by just walking/flying and loading chunks you want to load faster next time.
-Xisumavoid used teleport commands and a macro to do it( youtube.com/watch?v=eA35S2GW-jI ) but, the datapack does that for you.
**To anybody reading this please correct any miss-information you find**
thank you,
have aa nice day.

**Comment by nonetrix** [comment]
I'm on a fairly powerful system and I am having this issue even with generated worlds with Sodium Phosphor Lithium and all that I'll record it with obs and comment again

**Comment by nonetrix** [comment]
The game pretty much gives up with render distances like 128
